### ISSUE TITLE
GLIBC issue

### ISSUE THREAD

**Issue by tryphoncosinus** [ptahmose/MEXlibCZI#8]
Hello,

I try to export an image in czi format using MEXlibCZI  v0.3.2-alpha : an error occurs claiming GLIBC_2.38. Under Ubuntu 22.04, I have GLIBC 2.35. GLIBC cannot be easily updated without braking the OS. Is there any chance to get v0.3.2-alpha working with previous GLIBC versions ?

Thank you.

**Comment by tryphoncosinus** [comment]
I performed the code compilation (with cmake and make). I got the file MEXlibCZI.mexa64 and it works.

Now I am tying to understand how to write metadata.

Thank you for this amazing work!

**Comment by ptahmose** [comment]
Hmmm, I guess it should be easily possible to have a GH-actions-build with Ubuntu-22.04 - if this would solve the issues with glibc. I am not too familiar with how such woes are dealt with in Linux-world (other than - building it yourself). At least I learned (?) that linking glibc statically is considered a no-go (and not really possible?).

**Comment by tryphoncosinus** [comment]
That's why I prefer to not upgrade glibc. I have Ubuntu 24.04 but it takes time to maturate so that the tools I use becomes stable.

Thanks.

**Comment by ptahmose** [comment]
I added a build on Ubuntu22.04 to the GH-action. This release now has binaries built with Ubuntu22.04 and Ubuntu24.04.
